sudo: required
dist: xenial # (16.04)
# bionic (18.04) is not yet available in travis

language: cpp

cache:
  directories:
    - /home/travis/.ccache/

addons:
  apt:
    update: true

services:
  - mysql

git:
  depth: 1

matrix:
  include:
    - os: linux
      addons:
        apt:
          packages:
            - clang-3.8
      env:
        - CCOMPILERC="clang-3.8"
        - CCOMPILERCXX="clang++-3.8"

    - os: linux
      addons:
        apt:
          sources:
            - llvm-toolchain-xenial-7
          packages:
            - clang-7
      env:
        - CCOMPILERC="clang-7"
        - CCOMPILERCXX="clang++-7"

before_install:
  - sudo apt-get -y install build-essential libtool make cmake cmake-data openssl
  - sudo apt-get -y install libssl-dev libmysqlclient-dev libmysql++-dev libreadline6-dev zlib1g-dev libbz2-dev libace-dev
  - git config user.email "travis@build.bot" && git config user.name "Travis CI"
  - git tag -a -m "Travis build" init

install:
  - cd ..
  - git clone --depth=1 --branch=master https://github.com/azerothcore/azerothcore-wotlk.git azerothcore
  - mv mod-transmog azerothcore/modules
  - cd azerothcore
  - git submodule update --init --recursive

  - mysql -e "SET GLOBAL sql_mode = '';" # this is necessary because of mysql 5.7
  - mysql -uroot -e 'create database test_mysql;'
  - cd bin
  - cmake ../ -DCMAKE_C_COMPILER_LAUNCHER=ccache -DCMAKE_CXX_COMPILER_LAUNCHER=ccache -DCMAKE_C_COMPILER="${CCOMPILERC}" -DCMAKE_CXX_COMPILER="${CCOMPILERCXX}" -DWITH_WARNINGS=1 -DWITH_COREDEBUG=0 -DUSE_COREPCH=0 -DUSE_SCRIPTPCH=0 -DTOOLS=0 -DSCRIPTS=1 -DSERVERS=1 -DCMAKE_BUILD_TYPE=Release -DCMAKE_C_FLAGS="-Werror" -DCMAKE_CXX_FLAGS="-Werror" -DCMAKE_INSTALL_PREFIX=check_install
  - cd ..

script:
  - mysql -uroot < data/sql/create/create_mysql.sql
  - cat data/sql/base/db_auth/*.sql | mysql -uacore -pacore auth
  - cat data/sql/base/db_characters/*.sql | mysql -uacore -pacore characters
  - cat data/sql/base/db_world/*.sql | mysql -uacore -pacore world
  - cat data/sql/updates/db_auth/*.sql | mysql -uacore -pacore auth
  - cat data/sql/updates/db_characters/*.sql | mysql -uacore -pacore characters
  - cat data/sql/updates/db_world/*.sql | mysql -uacore -pacore world
  - mysql -uroot < data/sql/create/drop_mysql.sql
  - cd bin
  - export CCACHE_CPP2=true
  - ccache -s
  - make -j 4 -k && make install
  - ccache -s
  - cd check_install/bin
